name: inception

services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    secrets:
      - ssl_cert
      - ssl_key
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - wordpress
    restart: unless-stopped
    networks:
      - inception

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    secrets:
      - db_password
      - wp_admin_password
      - wp_user_password
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
      - WP_TITLE=${WP_TITLE}
      - WP_ADMIN_USER=${WP_ADMIN_USER}
      - WP_ADMIN_EMAIL=${WP_ADMIN_EMAIL}
      - WP_USER=${WP_USER}
      - WP_USER_EMAIL=${WP_USER_EMAIL}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_HOST=${DB_HOST}
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - mariadb
    restart: unless-stopped
    networks:
      - inception

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    secrets:
      - db_password
      - db_root_password
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - inception

secrets:
  ssl_cert:
    file: ../secrets/ssl_cert.txt
  ssl_key:
    file: ../secrets/ssl_key.txt
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
  wp_user_password:
    file: ../secrets/wp_user_password.txt

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/wordpress
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/mariadb

networks:
  inception: