
services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    env_file:
      - ./.env
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - wordpress
    restart: unless-stopped
    networks:
      - inception

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    secrets:
      - db_password
      - wp_admin_password
      - wp_user_password
    env_file:
      - ./.env
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - mariadb
    restart: unless-stopped
    networks:
      - inception

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    secrets:
      - db_password
      - db_root_password
    env_file:
      - ./.env
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - inception

secrets:
  db_password:
    file: ./../secrets/db_password.txt
  db_root_password:
    file: ./../secrets/db_root_password.txt
  wp_admin_password:
    file: ./../secrets/wp_admin_password.txt
  wp_user_password:
    file: ./../secrets/wp_user_password.txt

volumes:
  wordpress_data:
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/wordpress
  mariadb_data:
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/mariadb

networks:
  inception:
    driver: bridge